[openai]
api_key = "your_api_key_here""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"